Add FLCO-FLYCOLORF7MINI.config
betaflight/unified-targets pull request #1009
Opened 2023-05-16 03:33 UTC by tobeornottobe81

Add  FLCO-FLYCOLORF7MINI target

2023-05-16 03:55 UTC, tobeornottobe81 commented
![image](https://github.com/betaflight/unified-targets/assets/57481312/93dae3f2-a703-4fc6-97b5-c567c391ef4c)

Choose one or according to the actual product, thank you。

2023-05-16 09:30 UTC, haslinghuis requested changes

2023-05-16 09:30 UTC, haslinghuis commented on configs/default/FLCO-FLYCOLORF7MINI.config
> +#define USE_FLASH_M25Q128JV
```suggestion
#define USE_FLASH_W25Q128FV
```

2023-05-16 09:30 UTC, haslinghuis commented on configs/default/FLCO-FLYCOLORF7MINI.config
> +set debug_mode = GYRO_SCALED
Remove user settings
```suggestion
```

2023-05-16 09:30 UTC, haslinghuis commented on configs/default/FLCO-FLYCOLORF7MINI.config
> +set serialrx_provider = SBUS
Determined by cloud API
```suggestion
```

2023-05-16 09:30 UTC, haslinghuis commented on configs/default/FLCO-FLYCOLORF7MINI.config
> +set pid_process_denom = 4
Is this intended?
```suggestion
set pid_process_denom = 4
```

2023-05-17 00:39 UTC, haslinghuis approved these changes

2023-05-17 18:10 UTC, merged