Update SJET-AOCODARCF411_AIO.config
betaflight/unified-targets pull request #1013
Opened 2023-05-18 06:20 UTC by aocodarc

1.Added all possible sensors which can be present on all different variants of AOCODARC boards.
2.Removed some redundant code.

2023-05-18 06:57 UTC, blckmn approved these changes

2023-05-18 14:44 UTC, nerdCopter submitted a review, later dismissed

2023-05-18 14:58 UTC, haslinghuis requested changes

2023-05-18 14:58 UTC, haslinghuis commented on configs/default/SJET-AOCODARCF411_AIO.config
> +#define USE_FLASH_M25P16
```suggestion
#define USE_BARO
#define USE_BARO_BMP280
#define USE_BARO_DPS310
#define USE_FLASH
#define USE_FLASH_W25Q128FV

```

2023-05-18 14:59 UTC, haslinghuis commented on configs/default/SJET-AOCODARCF411_AIO.config
> +#define USE_FLASH_M25P16
M25P16 is automatically included when W25Q128FV is defined.

2023-05-20 01:34 UTC, haslinghuis approved these changes

2023-05-20 01:46 UTC, aocodarc commented
I have made the changes according to the prompts, thank you

2023-05-20 08:56 UTC, blckmn approved these changes

2023-05-20 08:57 UTC, merged