Create DARWINF722HD_SD target
betaflight/unified-targets pull request #1019
Opened 2023-05-26 13:00 UTC by DMAXYANG

It changed the flash to sd card on the DARWINF722HD target and added the 42688P gyro, 
Thank you

2023-05-29 10:09 UTC, DMAXYANG commented
> * the name contains `HD_SD`, is this wanted?
> * if nothing else changed except the gyro and sdcard, then why not just add those new things to the existing definitions?
Because some Custom Settings were also modified, these new Settings would affect pilots using the old target board

2023-06-01 22:20 UTC, haslinghuis commented
We need a new target as changing from flash to sdcard also requires default blackbox device change but would suggest renaming it to DARWINF722HDV2.

2023-06-05 04:31 UTC, DMAXYANG commented
> We need a new target as changing from flash to sdcard also requires default blackbox device change but would suggest renaming it to DARWINF722HDV2.

Hello,
I mainly consider that the V1 version will not be discontinued, and its Layout is also very different from the V1 version
![605122940](https://github.com/betaflight/unified-targets/assets/12828564/d88cd631-722e-49fe-939e-03baad9c0aa7)

Thanks

2023-06-05 10:41 UTC, haslinghuis requested changes

2023-06-05 10:41 UTC, haslinghuis commented on configs/default/DAFP-DARWINF722HD_SD.config
> +set dyn_notch_q = 500
Remove tuning (we have presets for tuning)
```suggestion


```

2023-06-05 10:41 UTC, haslinghuis commented on configs/default/DAFP-DARWINF722HD_SD.config
> +set serialrx_provider = CRSF
This will be defined using cloud build
```suggestion

```

2023-06-05 10:41 UTC, haslinghuis commented on configs/default/DAFP-DARWINF722HD_SD.config
> +set debug_mode = GYRO_SCALED
Remove debug
```suggestion

```

2023-06-05 10:41 UTC, haslinghuis commented on configs/default/DAFP-DARWINF722HD_SD.config
> +set gyro_1_align_yaw = 1800
Add new line
```suggestion
set gyro_1_align_yaw = 1800

```

2023-06-06 10:06 UTC, haslinghuis approved these changes

2023-06-06 14:25 UTC, haslinghuis commented
Agree

2023-06-07 03:53 UTC, DMAXYANG commented
> i still prefer `DARWINF722HDV2` rather than `DARWINF722HD_SD` only because pilots will read "SD" as standard definition not "sdcard". but this is just an opinion. thoughts @haslinghuis ?

All right, it's just a naming convention.

2023-06-07 06:01 UTC, sugaarK approved these changes

2023-06-07 10:30 UTC, haslinghuis approved these changes

2023-06-07 12:59 UTC, merged