Added new unif target: GEPRC Taker F722 SE
betaflight/unified-targets pull request #1044
Opened 2023-06-12 14:46 UTC by Guidus93

Added GEPRC TAKER F722SE config file

2023-06-12 14:52 UTC, nerdCopter commented
* will hardware have all those gyros?
* i dont think serial settings are supposed to be pre-defined
* i dont think ESC_SENSOR feature is suppose to be pre-defined -- may need verification from other devs.

2023-06-12 15:02 UTC, nerdCopter commented
thank you; please wait for other dev commentary.

2023-06-13 05:48 UTC, sugaarK submitted a review, later dismissed
Given the plug fest going on I think it’s ok to define some serial connections..  @Guidus93 coild you send a couple of samples out to the guys? I’ll give you addresses on discord

2023-06-19 09:44 UTC, haslinghuis requested changes

2023-06-19 09:44 UTC, haslinghuis commented on configs/default/GEPR-TAKER_F722SE.config
> +#define USE_SDCARD
USE_SDCARD needs to be removed.
```suggestion

```

2023-06-19 09:51 UTC, haslinghuis approved these changes

2023-06-20 12:41 UTC, nerdCopter approved these changes

2023-06-22 13:08 UTC, haslinghuis commented on configs/default/GEPR-TAKER_F722SE.config
> +#define USE_ACCGYRO_BMI270
BMI[270] is only recommended for STM32F4xx

2023-06-22 13:13 UTC, haslinghuis requested changes
Just only see now you did not create feature branch. I will create a new one.

2023-06-22 13:24 UTC, closed without merging