add new target FLMO-BANDERAF7.config
betaflight/unified-targets pull request #1111
Opened 2023-08-14 19:05 UTC by cvetaevvitaliy

add new target FLMO-BANDERAF7.config

2023-08-14 19:12 UTC, haslinghuis requested changes

2023-08-14 19:12 UTC, haslinghuis commented on configs/default/FLMO-BANDERAF7.config
> +#define USE_SERVOS
USE_SERVOS is a build option.
```suggestion

```

2023-08-14 19:12 UTC, haslinghuis commented on configs/default/FLMO-BANDERAF7.config
> +set pilot_name = STEPAN
No NAZI's allowed

```suggestion
```

2023-08-14 22:20 UTC, haslinghuis commented on configs/default/FLMO-BANDERAF7.config
> +feature GPS
```suggestion

```

2023-08-14 22:20 UTC, haslinghuis commented on configs/default/FLMO-BANDERAF7.config
> +set serialrx_provider = CRSF
Cloud based

```suggestion

```

2023-08-14 22:42 UTC, haslinghuis commented
@cvetaevvitaliy We are not going to allow the BANDERAF7 target naming. We are kind of shocked using ideology in FOSS. Can't wait for HITLERH7 or TRUMANH7 :grinning: 

Please leave politics = military outside of our project. Betaflight is for civilian use only. Any violations will be punished :rofl: 

As this PR is based upon master we cannot allow merging as we need a feature branch.

Note: bandera in Spanish means flag.

2023-08-14 22:46 UTC, closed without merging

2023-08-14 23:04 UTC, haslinghuis commented
@cvetaevvitaliy is the AI companion board sample ready. We like to investigate added functionality for civilian purposes.

Not build sky-net robots :grin: 

Life is about creation - not destruction.

2023-08-15 06:17 UTC, cvetaevvitaliy commented
> @cvetaevvitaliy is the AI companion board sample ready. We like to investigate added functionality for civilian purposes.
> 
> 
> 
> Not build sky-net robots :grin: 
> 
> 
> 
> Life is about creation - not destruction.

Tell that to the orcs who are killing my people on my land.

Github is not the place to discuss such topics.

2023-08-15 06:23 UTC, cvetaevvitaliy commented
Yep! This is the "FLAG" F7

I will fix the branch from the feature-branch, thank you understanding.