Hakrc1 utarget
betaflight/unified-targets pull request #1136
Opened 2023-09-02 03:23 UTC by hakrc1

add  a new target configs\default\SU25-SUB250REDFOXF722AIO.config

2023-09-02 15:32 UTC, haslinghuis requested changes

2023-09-02 15:32 UTC, haslinghuis commented on configs/default/GEPR-TAKERF411.config
> +board_name TAKERF411
We already have TAKERF411 target which already is present 😕

2023-09-02 15:32 UTC, haslinghuis commented on configs/default/SU25-SUB250REDFOXF722AIO.config
> +set align_board_yaw = -45
```suggestion
set align_board_yaw = -45

```

2023-09-04 19:04 UTC, nerdCopter approved these changes

2023-09-04 21:58 UTC, haslinghuis approved these changes

2023-09-04 21:58 UTC, merged