Upload file f7miniv2
betaflight/unified-targets pull request #1145
Opened 2023-09-07 13:07 UTC by aocodarc

Upload file f7miniv2

2023-09-09 19:22 UTC, haslinghuis requested changes

2023-09-09 19:22 UTC, haslinghuis commented on configs/default/SJET-AOCODAF722MINIV2.config
> +set max7456_clock = NOMINAL
Please remove default values:

```suggestion
```

2023-09-09 19:22 UTC, haslinghuis commented on configs/default/SJET-AOCODAF722MINIV2.config
> +set usb_msc_pin_pullup = ON
Please remove default values:
```suggestion
```

2023-09-12 14:08 UTC, aocodarc commented
I have deleted the default configuration

2023-09-13 07:39 UTC, haslinghuis approved these changes

2023-09-13 13:03 UTC, nerdCopter approved these changes

2023-09-13 13:37 UTC, merged

2024-04-29 18:34 UTC, nerdCopter commented on configs/default/SJET-AOCODAF722MINIV2.config
> +# pin A15: TIM8 CH4 (AF1)
@aocodarc , these comments and pins do not match.