Create DFRC-DREAMFLYF411.config
betaflight/unified-targets pull request #1208
Opened 2023-11-29 14:06 UTC by GEME-Cyi

Add DFRC-DREAMFLYF411_support

2023-11-29 14:30 UTC, nerdCopter commented
![image](https://github.com/betaflight/unified-targets/assets/56646290/2c65bd18-56d2-4979-8978-d1ed34d6aa3d)

recommended git global environment:

windows:
```
git config --global core.autocrlf true
```
linux/osx:
```
git config --global core.autocrlf input
```
cross-platform:
```
git config --global core.safecrlf warn
git config --global core.whitespace cr-at-eol
git config --global core.filemode false
git config --global help.autocorrect true
```

2023-11-29 16:04 UTC, haslinghuis requested changes

2023-11-29 16:04 UTC, haslinghuis commented on configs/default/DFRC-DREAMFLYF411.config
> +feature LED_STRI
```suggestion
feature LED_STRIP
```

2023-11-29 16:04 UTC, haslinghuis commented on configs/default/DFRC-DREAMFLYF411.config
> +feature SOFTSERIAL
```suggestion

```

No softserial pins defined

2023-11-29 16:04 UTC, haslinghuis commented on configs/default/DFRC-DREAMFLYF411.config
> +set gyro_1_sensor_align = CW270
No newline at EOF
```suggestion
set gyro_1_sensor_align = CW270

```

2023-11-30 09:14 UTC, haslinghuis approved these changes

2023-11-30 15:05 UTC, nerdCopter approved these changes

2023-11-30 16:19 UTC, merged