Fix AOCODARC_F405V3 target naming convention
betaflight/unified-targets pull request #1246
Opened 2024-01-27 04:25 UTC by lida2003

2024-01-27 11:53 UTC, haslinghuis requested changes
![image](https://github.com/betaflight/unified-targets/assets/8344830/239de683-50cb-491a-acab-52d1e474b38d)

Suggest we use AOCODARCF405V3

2024-01-28 00:30 UTC, haslinghuis approved these changes

2024-01-28 00:31 UTC, lida2003 commented
> Suggest we use AOCODARCF405V3

Thanks. Now we have the naming rules for Aocoda-RC products.

2024-01-29 14:13 UTC, nerdCopter approved these changes

2024-01-29 14:27 UTC, merged