add a new target RUSH-BLADE_F4
betaflight/unified-targets pull request #1275
Opened 2024-03-14 06:54 UTC by hakrc1

add a new target RUSH-BLADE_F4

2024-03-14 07:16 UTC, hakrc1 commented
@haslinghuis Hi，about“ERROR: Invalid characters found in board_name”。I don't understand which character of "RUSH-BLADE_F4" is invalid.

2024-03-14 08:10 UTC, pfeerick requested changes

2024-03-14 08:10 UTC, pfeerick commented on configs/default/RUSH-BLADE_F4.config
> +manufacturer_id  RUSH
```suggestion
board_name BLADE_F4
manufacturer_id RUSH
```
You have an extra space between the parameter and the value...

2024-03-14 08:38 UTC, haslinghuis commented on configs/default/RUSH-BLADE_F4.config
> +set flash_spi_bus = 2
Sharing SPI is not recommended and will have negative performance impact for blackbox and OSD.

2024-03-14 08:59 UTC, haslinghuis approved these changes
Sharing SPI is not recommended and will have negative performance impact for blackbox and OSD.

2024-03-15 02:08 UTC, hakrc1 commented
OK.Regarding the SPI sharing , we will advise our customers.Thanks for the heads up.

2024-03-19 18:09 UTC, nerdCopter approved these changes

2024-03-19 22:39 UTC, merged