Add target NBD_INFINITYAIO255
betaflight/unified-targets pull request #1299
Opened 2024-04-07 10:12 UTC by mywinchester

Add target for `NEBD-NBD_INFINITYAIO255`, File already minimize and tested in hardware. 

Please notice me for any issues.

2024-04-17 14:11 UTC, nerdCopter commented
will need sync to https://github.com/betaflight/config as well.

2024-04-17 14:16 UTC, nerdCopter commented
seems that GPS and LED_STRIP should not be enabled in the defines.

2024-04-30 06:23 UTC, mywinchester commented
> seems that GPS and LED_STRIP should not be enabled in the defines.

Sorry for the latency, already fixed that in new commit.

2024-04-30 12:43 UTC, nerdCopter commented
@haslinghuis , anything else this needs?

2024-04-30 12:43 UTC, nerdCopter submitted a review, later dismissed

2024-05-07 09:55 UTC, mywinchester commented on configs/default/NEBD-NBD_INFINITYAIO255.config
> +set mag_bustype = I2C
Thanks, I added it in latest commit, please check.

2024-05-07 12:10 UTC, haslinghuis commented on configs/default/NEBD-NBD_INFINITYAIO255.config
> +set osd_canvas_height = 13
canvas depends on build options.

```suggestion
```

2024-05-07 12:10 UTC, haslinghuis requested changes

2024-05-07 12:10 UTC, haslinghuis commented on configs/default/NEBD-NBD_INFINITYAIO255.config
> +set osd_canvas_height = 13
canvas depends on build options.

```suggestion
```

2024-05-07 12:20 UTC, haslinghuis approved these changes

2024-05-07 12:38 UTC, nerdCopter approved these changes

2024-05-07 13:14 UTC, merged