Add DYS F4 4530D unified target. http://www.dys.hk/product/648.html#
betaflight/unified-targets pull request #420
Opened 2021-01-11 21:15 UTC by apeelme

2021-01-11 21:29 UTC, mikeller requested changes
@apeelme: Are you the official target maintainer for the DYS manufacturer?

2021-01-11 21:29 UTC, mikeller commented on configs/default/DYST-DYSF44530D.config
> +board_name DYSF44530D
Please read and follow the instructions on https://github.com/betaflight/unified-targets (**including testing**) - this was clearly not done by following the instructions, as it is missing the first line.

2021-01-11 21:29 UTC, mikeller commented on configs/default/DYST-DYSF44530D.config
> +set mag_hardware = NONE
There is no reason to set this - leaving the default will work just fine with no magnetometer / barometer connected. If you set this, all users wanting to use a magnetometer / barometer will be advised to buy a new flight controller from a different manufacturer in order to get magnetometer / barometer support, as this is not supported by this hardware.

2021-01-11 21:29 UTC, mikeller commented on configs/default/DYST-DYSF44530D.config
> +set baro_hardware = NONE
There is no reason to set this - leaving the default will work just fine with no magnetometer / barometer connected. If you set this, all users wanting to use a magnetometer / barometer will be advised to buy a new flight controller from a different manufacturer in order to get magnetometer / barometer support, as this is not supported by this hardware.

2021-01-11 21:29 UTC, mikeller commented on configs/default/DYST-DYSF44530D.config
> +feature -SOFTSERIAL
Please follow the instructions - default settings are not permissible in Unified Target configurations.

2021-01-11 21:31 UTC, apeelme commented
> @apeelme: Are you the official target maintainer for the DYS manufacturer?

No.

2021-01-13 07:27 UTC, mikeller approved these changes

2021-01-13 07:27 UTC, merged