Add EACHINEF411_AIO.config
betaflight/unified-targets pull request #503
Opened 2021-08-28 08:04 UTC by EachineRC

Add EACHINEF411_AIO.config

2021-08-30 01:42 UTC, DusKing1 requested changes

2021-08-30 01:42 UTC, DusKing1 commented on configs/default/EACH-EACHINEF411_AIO.config
> +# name
Should be removed

2021-08-30 06:22 UTC, EachineRC commented on configs/default/EACH-EACHINEF411_AIO.config
> +# name
Thanks for your reminder.

2021-08-30 06:37 UTC, DusKing1 approved these changes

2021-09-06 01:47 UTC, mikeller approved these changes

2021-09-06 01:47 UTC, merged