Add new target NEUTRONRCF4
betaflight/unified-targets pull request #527
Opened 2021-11-12 06:46 UTC by DusKing1

2021-11-16 05:15 UTC, limonspb requested changes

2021-11-16 05:15 UTC, limonspb commented on configs/default/NERC-NEUTRONRCF407.config
> +set gyro_1_sensor_align = CW270
new line

2021-11-16 05:15 UTC, limonspb commented on configs/default/NERC-NEUTRONRCF407.config
> +set serialrx_provider = SBUS
is that AIO?

2021-11-16 05:29 UTC, DusKing1 commented on configs/default/NERC-NEUTRONRCF407.config
> +set serialrx_provider = SBUS
no

2021-11-23 02:25 UTC, haslinghuis approved these changes

2021-11-23 02:25 UTC, merged