Add SNMT NvisionF405&F411 unified config file
betaflight/unified-targets pull request #549
Opened 2022-01-01 19:20 UTC by MrXueyuan

2022-01-01 19:41 UTC, Asizon commented
This is really wrong, pmease read unified targets manual in our repo.

2022-01-01 19:50 UTC, MrXueyuan commented
Sorry，I found some errors in the NVision FPV product configuration file. I will make corrections.

2022-01-01 19:57 UTC, haslinghuis commented
@MrXueyuan please do that on the same PR! Read the documentation carefully. Don't use dumps or diffs statements inside the config file.

2022-01-01 20:24 UTC, MrXueyuan commented
OK, I corrected some of the code again. Thinks

2022-01-01 20:28 UTC, haslinghuis commented
@MrXueyuan please follow instructions here:

https://github.com/betaflight/betaflight/blob/master/docs/TargetMaintenance/CreatingAUnifiedTarget.md

2022-02-03 08:21 UTC, MrXueyuan commented
I corrected some of the code again. Please review.

2022-02-03 12:06 UTC, haslinghuis commented on configs/default/SNMT-NVISIONF405.config
> +feature -RX_PPM
These are not needed

2022-02-03 12:09 UTC, haslinghuis commented on configs/default/SNMT-NVISIONF411.config
> +feature -RX_PPM
Not needed:
https://github.com/betaflight/unified-targets/pull/549/files#diff-84ccb6dbbadb23d59bfd5c578f2df3462be48afd991f71d3b15c0a36c3c222dbR97-R119

2022-02-03 12:09 UTC, haslinghuis commented on configs/default/SNMT-NVISIONF722.config
> +# Betaflight / STM32F405 (S405) 4.2.10 Sep 30 2021 / 11:29:38 (e4b212699) MSP API: 1.43
Wrong MCU. Also the PR does only adding F405 and F411

2022-02-03 12:10 UTC, haslinghuis commented on configs/default/SNMT-NVISIONF722.config
> +feature -RX_PPM
Remove these lines:
https://github.com/betaflight/unified-targets/pull/549/files#diff-b37b80a009d8fbf654e14bb1bec6e1bd80f58cc3788131695c80ae123f0dadc6R97-R119

2022-02-03 12:16 UTC, haslinghuis commented on configs/default/SNMT-NVISIONF405.config
> +serial 20 1 115200 57600 0 115200
https://github.com/betaflight/unified-targets/pull/549/files#diff-d33a055792397d139e9eddc57e3e04338b006af367e87c916a0e00291fda675cR131-R137

2022-02-03 12:18 UTC, haslinghuis requested changes
There are many more configurations already default.

2022-02-04 04:56 UTC, DusKing1 requested changes

2022-02-04 04:56 UTC, DusKing1 commented on configs/default/SNMT-NVISIONF405.config
> +manufacturer_id SNMT
What's this?

2022-02-04 06:22 UTC, Asizon commented
These config files continues really wrong, please read instructions how to get config from a legacy target @MrXueyuan

2022-03-14 04:40 UTC, closed without merging