Added anyleaf mercury g4
betaflight/unified-targets pull request #572
Opened 2022-03-17 19:48 UTC by David-OConnor

Draft / WIP. Will not be ready to merge until tested on hardware, which is still in development.

Notes:
- Do any changes need to be made on the main Betaflight repo? Instructions are a bit ambiguous about when you also need a legacy config.
- Uses STM32G4 MCU. G4 is supported on a few existing variants, but isn't listed in [the table here](https://github.com/betaflight/betaflight/blob/master/docs/TargetMaintenance/CreatingAUnifiedTarget.md). The variant used by this (Currently G431) should be very similar on the hardware / firmware-programming level.
- Uses onboard ELRS, via a SX1280 chip connected to SPI. There are a few boards that are advertised as supporting this, but I can't find their configs in this repo to use as an example. (Which in itself is odd!)
- There is most certainly incorrect syntax, eg on the first line, and where indicated by comments, eg for DMA, and related to ELRS.

2022-03-18 01:39 UTC, DusKing1 requested changes

2022-03-18 01:39 UTC, DusKing1 commented on configs/default/ANYL-MERCURYG4.config
> +# Betaflight / STM32G431 (SH74) 4.3.0 March 17 2022 / 00:00:00 (ee740d1) MSP API: 1.44
what's this? `STM32G431 (SH74)`

2022-03-18 21:41 UTC, David-OConnor commented on configs/default/ANYL-MERCURYG4.config
> +# Betaflight / STM32G431 (SH74) 4.3.0 March 17 2022 / 00:00:00 (ee740d1) MSP API: 1.44
No idea!

2022-03-18 22:53 UTC, Asizon commented on configs/default/ANYL-MERCURYG4.config
> +# Betaflight / STM32G431 (SH74) 4.3.0 March 17 2022 / 00:00:00 (ee740d1) MSP API: 1.44
Lol?

2022-03-18 22:56 UTC, Asizon commented
@David-OConnor Please don't send pr without knowing what you are doing

2022-03-18 23:30 UTC, David-OConnor commented
> @David-OConnor Please don't send pr without knowing what you are doing

Don't be an ass. I made a good faith effort, submitted a *draft* PR, and asked for feedback.

So, let's be specific. What should I change?

2022-03-19 00:19 UTC, David-OConnor commented
https://github.com/betaflight/unified-targets/pull/574

2022-03-19 00:25 UTC, haslinghuis commented on configs/default/ANYL-MERCURYG4.config
> +# Betaflight / STM32G431 (SH74) 4.3.0 March 17 2022 / 00:00:00 (ee740d1) MSP API: 1.44
```suggestion
# Betaflight / STM32G47X (SG47) 4.3.0 March 17 2022 / 00:00:00 (ee740d1) MSP API: 1.44
```

2022-03-19 00:26 UTC, haslinghuis commented on configs/default/ANYL-MERCURYG4.config
> +#set pinio_box = 40,41,255,255 # ??
See: https://github.com/betaflight/betaflight/wiki/Pinio-and-PinioBox

2022-03-19 00:27 UTC, haslinghuis commented on configs/default/ANYL-MERCURYG4.config
> +
👾 (unneeded extra line)

2022-03-19 00:27 UTC, haslinghuis commented on configs/default/ANYL-MERCURYG4.config
> +
👾 (unneeded extra line)

2022-03-19 13:29 UTC, Asizon commented
> > @David-OConnor Please don't send pr without knowing what you are doing
> 
> Don't be an ass. I made a good faith effort, submitted a _draft_ PR, and asked for feedback.
> 
> So, let's be specific. What should I change?

@David-OConnor who is an ass? You should try this on a real target before push a PR on Betaflight oficial repo, dotn waste reviewers time please.

2022-03-19 18:16 UTC, haslinghuis commented
@David-OConnor please follow our rules. I'm closing this for now as the hardware does not seem to be ready yet.

Example: https://github.com/betaflight/unified-targets/pull/520#issuecomment-955683903

Also please don't be offensive or confrontational and read https://github.com/betaflight/betaflight/blob/master/CODE_OF_CONDUCT.md

2022-03-19 18:16 UTC, closed without merging