Add RacerStar MINI_H743-HD
betaflight/unified-targets pull request #585
Opened 2022-04-15 11:23 UTC by howels

Adding the [RacerStar board](https://m.racerstar.com/20x20mm-racerstar-mini-h743-hd-3-6s-aio-betaflight-flight-controller-w-or-3a-5a-bec-for-rc-fpv-racing-drone-p-461.html) which has been on the market some time but is shipping with a heavily modified IFLIGHT_H743_AIO configuration. This PR adds the Racerstar MINI_H743-HD properly and allows users to upgrade to 4.3 more easily.

2022-04-15 13:10 UTC, haslinghuis requested changes
Please also rename the filename accordingly.

2022-04-15 13:10 UTC, haslinghuis commented on configs/default/RAST-MINI_H743-HD.config
> +board_name MINI_H743-HD
```suggestion
board_name H743MINI
```

```
Checking target naming...
ERROR: Invalid characters found in board_name (MINI_H743-HD, allowed 'A'-'Z', '0'-'9', '_') in
Unified Target configuration configs/default/RAST-MINI_H743-HD.config.
```

2022-04-15 13:14 UTC, howels commented
> Please also rename the filename accordingly.

Sure, will update

2022-04-15 14:10 UTC, howels commented on configs/default/RAST-MINI_H743-HD.config
> +board_name MINI_H743-HD
Renamed and checks passed.

2022-04-15 20:42 UTC, haslinghuis approved these changes

2022-04-15 22:01 UTC, merged

2022-07-20 17:12 UTC, kritical90 commented
ami los motores no 2 de ellos no giran e probado otra fc para descartar esc y funciona correctamente esta fc esta mal el firmware es imposible hacer funcionar los 4 motores solo funciona el 1 y el 2 e intentado cambiar el resource y nada no tengo ni idea alguien que pueda ayudar porque como yo estamos mas personas