Create SJET-AOCODAF405V2.config
betaflight/unified-targets pull request #634
Opened 2022-06-28 03:48 UTC by aocodarc

Following everyone's suggestion, new board aocodaf405 v1.1 uses target "SJET-AOCODAF405V2".
Thank you for what you did！

2022-06-28 21:35 UTC, haslinghuis requested changes

2022-06-28 21:35 UTC, haslinghuis commented on configs/default/SJET-AOCODAF405V2.config
> +# Betaflight / STM32F405 (S405) 4.2.11 Nov  9 2021 / 20:27:49 (948ba6339) MSP API: 1.43
Should we update using 4.3?

2022-06-29 01:02 UTC, DusKing1 reviewed
Your definition of " everyone" is pretty monstrous.

2022-06-29 01:22 UTC, haslinghuis submitted a review, later dismissed

2022-06-29 01:26 UTC, haslinghuis commented on configs/default/SJET-AOCODAF405V2.config
> +serial 20 1 115200 57600 0 115200
Is this not the default ?

2022-07-04 03:01 UTC, haslinghuis approved these changes

2022-07-06 14:09 UTC, merged