Add config for GEELANGF411 board
betaflight/unified-targets pull request #642
Opened 2022-07-08 14:51 UTC by Linjieqiang

2022-07-08 23:20 UTC, haslinghuis requested changes

2022-07-08 23:20 UTC, haslinghuis commented on configs/default/GEEL-GEELANGF411.config
> +set motor_pwm_protocol = DSHOT600
Please remove if not an AIO board

2022-07-08 23:20 UTC, haslinghuis commented on configs/default/GEEL-GEELANGF411.config
> +feature -RX_PARALLEL_PWM
Please remove. We have change the default to `RX_SERIAL`

2022-07-08 23:20 UTC, haslinghuis commented on configs/default/GEEL-GEELANGF411.config
> +resource SERIAL_RX 2 A03
resource is already assigned to PPM 1

2022-07-08 23:20 UTC, haslinghuis commented on configs/default/GEEL-GEELANGF411.config
> +resource SERIAL_RX 11 B10
resource is already assigned to MOTOR 6

2022-07-08 23:20 UTC, haslinghuis commented on configs/default/GEEL-GEELANGF411.config
> +serial 0 8192 115200 57600 0 115200
Does this board has a TRAMP on board?

2022-07-08 23:20 UTC, haslinghuis commented on configs/default/GEEL-GEELANGF411.config
> +set blackbox_p_ratio = 16
What's this?

2022-07-08 23:20 UTC, haslinghuis commented on .github/CODEOWNERS
> +/configs/default/GEEL-* @Linjieqiang @betaflight/unified-target-administrators
This should be done in a separate PR.

2022-07-09 02:40 UTC, Linjieqiang commented
@haslinghuis Thanks. I will fix them later.

2022-07-14 02:25 UTC, Linjieqiang commented on configs/default/GEEL-GEELANGF411.config
> +set motor_pwm_protocol = DSHOT600
It's a AIO board. 
so keep them.

2022-07-14 02:27 UTC, Linjieqiang commented on configs/default/GEEL-GEELANGF411.config
> +serial 0 8192 115200 57600 0 115200
Yes, it integrates.

2022-07-14 02:28 UTC, Linjieqiang commented on configs/default/GEEL-GEELANGF411.config
> +set blackbox_p_ratio = 16
Removed "set blackbox_p_ratio = 16"

2022-07-14 02:28 UTC, Linjieqiang commented on .github/CODEOWNERS
> +/configs/default/GEEL-* @Linjieqiang @betaflight/unified-target-administrators
OKAY

2022-07-14 02:29 UTC, Linjieqiang commented
I have found your request to modify, please check, thanks. @haslinghuis

2022-07-14 02:46 UTC, KarateBrot requested changes

2022-07-14 02:46 UTC, KarateBrot commented on configs/default/GEEL-GEELANGF411.config
> +set gyro_1_align_yaw = 1800
```suggestion
set gyro_1_align_yaw = 1800

```
Missing end of line

2022-08-10 04:48 UTC, DusKing1 approved these changes

2022-08-10 05:03 UTC, KarateBrot approved these changes

2022-08-10 09:10 UTC, haslinghuis approved these changes

2022-08-10 09:10 UTC, merged

2022-10-22 16:58 UTC, Asizon commented
@Linjieqiang this target wont work without cpu definitions