Add new target FLYWOOF405NANO,F405PRO Config
betaflight/unified-targets pull request #658
Opened 2022-07-25 10:50 UTC by flywoo

Add new target FLYWOOF405NANO,F405PRO Config

2022-07-30 22:32 UTC, haslinghuis submitted a review, later dismissed

2022-07-31 03:38 UTC, DusKing1 requested changes

2022-07-31 03:38 UTC, DusKing1 commented on configs/default/FLWO-FLYWOOF405PRO.config
> +set gyro_2_spibus = 1
Where's the second gyro?

2022-07-31 03:38 UTC, DusKing1 commented on configs/default/FLWO-FLYWOOF405NANO.config
> +set gyro_2_spibus = 1
Where's the second gyro?

2022-07-31 03:38 UTC, DusKing1 commented on configs/default/FLWO-FLYWOOF405NANO.config
> +set gyro_1_sensor_align = DEFAULT
Why youe keep default here?

2022-08-01 02:13 UTC, flywoo commented on configs/default/FLWO-FLYWOOF405PRO.config
> +set gyro_2_spibus = 1
I will fix it, thanks

2022-08-01 02:13 UTC, flywoo commented on configs/default/FLWO-FLYWOOF405NANO.config
> +set gyro_2_spibus = 1
I will fix it, thanks

2022-08-01 02:14 UTC, flywoo commented on configs/default/FLWO-FLYWOOF405NANO.config
> +set gyro_1_sensor_align = DEFAULT
I will fix it, thanks

2022-08-05 02:19 UTC, DusKing1 requested changes

2022-08-05 02:19 UTC, DusKing1 commented on configs/default/FLWO-FLYWOOF405PRO.config
> +set gyro_1_align_yaw = 1800
EOL

2022-08-05 02:19 UTC, DusKing1 commented on configs/default/FLWO-FLYWOOF405NANO.config
> +set gyro_1_spibus = 1
EOL

2022-08-09 03:10 UTC, flywoo commented on configs/default/FLWO-FLYWOOF405NANO.config
> +set gyro_1_spibus = 1
fixed, thanks

2022-08-09 03:11 UTC, flywoo commented on configs/default/FLWO-FLYWOOF405PRO.config
> +set gyro_1_align_yaw = 1800
fixed, thanks

2022-08-09 08:02 UTC, haslinghuis approved these changes

2022-08-10 01:58 UTC, KarateBrot approved these changes

2022-08-10 02:00 UTC, merged