Add AOCODAF4V11 target
betaflight/unified-targets pull request #671
Opened 2022-08-31 11:15 UTC by ASDosjani

I have this FC but there was not target for it. I saved a dump and diff and compared it to the V2 target. It's almost the same, only the gyro alignment was different so that's why I'm making this PR. Now it's working perfectly.
@aocodarc please check this.

2022-08-31 11:36 UTC, Asizon commented
Hello, thought that no new target is needed if the only change is gyro aligment.

2022-08-31 11:58 UTC, ASDosjani commented
> Hello, I think that no new target is needed if the only change is gyro aligment.

Alright but than why the V2 is even exist? I didn't find a board for this target. If it is designed for this v1.1 than why the gyro alignment missing?

2022-10-03 21:52 UTC, KarateBrot commented
Adding it makes sense if there is a V1.1 out but it differs from V1.0

2022-10-03 22:23 UTC, haslinghuis submitted a review, later dismissed

2022-10-03 22:25 UTC, haslinghuis commented
We need to convert this to manufacturer presets with versioning in the new build system

2022-10-03 22:42 UTC, ASDosjani commented
I experienced in the meantime that `ibata_scale` is completely off. I think they just wrote some value completely random. The correct value is around 65 in my opinion. Is there any good way to determine this from the components? For example from resistor values if the FC use a voltage divider.

2022-10-03 23:06 UTC, ASDosjani commented
@KarateBrot I didn't found a single piece information about the V2 board. I think it was originally designed for my V1.1 but the naming changed. @aocodarc can you confirm this? I can make this PR to fix the gyro alignment only in the V2 config file.

2022-10-19 11:06 UTC, ASDosjani commented
I updated this PR, please reade first comment.

2022-10-19 22:37 UTC, haslinghuis commented
This PR is missing #defines for hardware being used.
Also don't include hardware (gyro) options in target naming.

2022-10-20 07:35 UTC, ASDosjani commented
> This PR is missing #defines for hardware being used. Also don't include hardware (gyro) options in target naming.

What do you recommend for the naming?
Are these #defines required for the new build system?

2022-10-20 10:51 UTC, sugaarK commented
> > This PR is missing #defines for hardware being used. Also don't include hardware (gyro) options in target naming.
> 
> What do you recommend for the naming? Are these #defines required for the new build system?

Yeah you do… 

Here is an example of the new defines..  

https://github.com/betaflight/unified-targets/blob/master/configs/default/AIRB-NOX.config

2022-10-20 11:32 UTC, ASDosjani commented
> Yeah you do…
> 
> Here is an example of the new defines..
> 
> https://github.com/betaflight/unified-targets/blob/master/configs/default/AIRB-NOX.config

Can I use #if to change the gyro rotation based on the gyroscope?

2022-10-20 11:48 UTC, sugaarK commented
> > Yeah you do…
> > Here is an example of the new defines..
> > https://github.com/betaflight/unified-targets/blob/master/configs/default/AIRB-NOX.config
> 
> Can I use #if to change the gyro rotation based on the gyroscope?

You’d define it like this 

set gyro_1_sensor_align = CW90FLIP
 set gyro_1_align_pitch = 1800
 set gyro_1_align_yaw = 900

2022-10-20 11:48 UTC, sugaarK commented
As you would in cli

2022-10-20 16:53 UTC, ASDosjani commented
> As you would in cli

Okay, but the problem is that there are two version of the board with two different gyro and their rotation is different, that's why I made two targets. Is it okay?

2022-10-20 21:04 UTC, haslinghuis commented
Yes targets with v1, v11, v2 should be okay if manufacturer uses the same revisions.

2022-10-20 22:19 UTC, ASDosjani commented
> Yes targets with v1, v11, v2 should be okay if manufacturer uses the same revisions.
> 
> The defines will allow to make use of the hardware in the configuration, so #else does not work here 🤔
> 
> As this is in final development stage we don't have any updated documentation yet.

I wasn't clear, sorry. There is no V2 board in existence however the target was made for the v1.1 hardware. The manufacturer don't want to make a v1.1 target instead he want to rename his hardware to v2. So the problem here is that this board can be ordered with mpu6000 or mpu6500 but the gyro alignment is different for this two but the FC is the same. So I made two targets with the correct alignment based on the used gyro. I will add the #define lines as soon as we clear this out.

2022-10-20 22:40 UTC, haslinghuis commented
aocoda should decide on versioning. If they don't want another version so be it. We have to direct support about it to aocoda.

2022-10-20 22:43 UTC, ASDosjani commented
>

2022-10-20 22:48 UTC, ASDosjani commented
Will this new build system be capable of running these custom cli command based on the definitions? Or how should I solve this two different gyro alignment?
I can give you Aocodarc availability if I understand the last sentence correctly.

2022-10-20 22:59 UTC, haslinghuis commented
No. The definitions only pull in required firmware parts for the target to build. So we need another version or use presets for the same board.

2022-10-20 23:01 UTC, ASDosjani commented
> No. The definitions only pull in required firmware parts for the target to build. So we need another version or use presets for the same board.

Okay, the presets are overkill in my opinion and not everyone use them so can I stick with this two target? I will add the #defines tomorrow.

2022-10-21 17:37 UTC, ASDosjani commented
@haslinghuis I added the #defines

2022-10-21 23:51 UTC, haslinghuis approved these changes

2022-10-24 05:07 UTC, Asizon requested changes
@aocodarc what do you think about adding that targets? Thry are necessary?

2022-10-27 09:37 UTC, Asizon approved these changes

2022-10-27 12:56 UTC, merged