Modify the EMAX board name for better identification
betaflight/unified-targets pull request #719
Opened 2022-11-10 03:06 UTC by EmaxModel

2022-11-11 06:05 UTC, sugaarK requested changes
These are all missing the new hardware defines needed for the new build system. 

https://github.com/betaflight/betaflight/blob/master/docs/TargetMaintenance/CreatingAUnifiedTarget.md#23-add-defines-for-hardware-drivers

2022-11-11 21:54 UTC, blckmn approved these changes

2022-11-16 13:06 UTC, haslinghuis approved these changes

2022-11-16 13:29 UTC, sugaarK approved these changes

2022-11-16 14:30 UTC, merged