Added DAKE-DAKEFPVF405 target
betaflight/unified-targets pull request #744
Opened 2022-12-11 11:06 UTC by ThanYangFPV

Hello, Added DAKE DAKEFPVF405 unif target (include hw define)

2022-12-11 14:32 UTC, haslinghuis requested changes

2022-12-11 14:32 UTC, haslinghuis commented on configs/default/DAKE-DAKEFPVF405.config
> +#define USE_BARO_BMP280
Please remove as the board uses SPI for baro.

2022-12-11 14:32 UTC, haslinghuis commented on configs/default/DAKE-DAKEFPVF405.config
> +feature RX_SERIAL
Please remove as it's default

2022-12-11 14:32 UTC, haslinghuis commented on configs/default/DAKE-DAKEFPVF405.config
> +set mag_i2c_device = 1
Please remove as there is no compass on board.

2022-12-11 14:32 UTC, haslinghuis commented on configs/default/DAKE-DAKEFPVF405.config
> +set gyro_1_align_yaw = 2700
Add new line
```suggestion
set gyro_1_align_yaw = 2700

```

2022-12-12 14:41 UTC, ThanYangFPV commented
ok,I made changes, please check. thanks.

2022-12-12 18:04 UTC, haslinghuis approved these changes

2022-12-12 18:50 UTC, KarateBrot approved these changes

2022-12-12 23:04 UTC, merged